// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHvwy60tY0IQoxueNT_ABxfG988SQEKjg',
    appId: '1:624197309115:web:861d0c5c2a1dcb39a64f9e',
    messagingSenderId: '624197309115',
    projectId: 'trip-planner-6747a',
    authDomain: 'trip-planner-6747a.firebaseapp.com',
    storageBucket: 'trip-planner-6747a.appspot.com',
    measurementId: 'G-J5314P4KE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIG8mhEoNBempJCCGUZToswcVuMHBcYLQ',
    appId: '1:624197309115:android:c6599678b533c23ca64f9e',
    messagingSenderId: '624197309115',
    projectId: 'trip-planner-6747a',
    storageBucket: 'trip-planner-6747a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkY9wyO0BnYpRqPfB_fvsqeEelnROyM_0',
    appId: '1:624197309115:ios:5ecb0e3c769178b4a64f9e',
    messagingSenderId: '624197309115',
    projectId: 'trip-planner-6747a',
    storageBucket: 'trip-planner-6747a.appspot.com',
    iosBundleId: 'com.example.tripPlannerFlutter',
  );
}
